### ISSUE TITLE
Help getting it to work?

### ISSUE THREAD

**Issue by benbowen** [DGadaleta88/data_curation_workflow#1]
Hi, I'm interested in resolving tautomers! Can you help me get your knime example working?  I'm following the directions to the best of my ability, but it seems like my input format is wrong.  Can you say whats wrong?  I followed the README.

My excel file looks like this:

```
ID	Name	CAS_NO
8868	Ethyl Acetoacetate	141-97-9
```

**Comment by DGadaleta88** [comment]
Hi, the input format seems correct to me. What kind of error do you observe? Can you please send me the entire (or part of) your input so I can try to understand the problem?

**Comment by benbowen** [comment]
@DGadaleta88 sorry for the huge delay and thanks for responding.  I'll start off by saying that my goal is to understand how your tool can standardize the position of mobile elements in chemical structures.  I mainly use rdkit in python, and I maintain a large compound database.  I have tons of problems standardizing chemical structures! That's what drew me to your paper.

I've never used knime; so I will document my steps here as best I can:

![image](https://user-images.githubusercontent.com/810953/52352354-4b58c500-29e1-11e9-90d6-803ca536fdeb.png)

Select "compound_input.xlsx".  Available here: https://drive.google.com/file/d/1hPomUYYooZpDGx1_ZIVkEkcgs6ztzaTL/view?usp=sharing

Highlight all nodes in workflow graph.

Click green play button in top nav bar

Here is my console:

```
WARN  File Upload          0:1446:0:1417 No such file: "/Applications/KNIME 3.7.0.app/Contents/MacOS/C:\Users\dgadaleta\Desktop\input_datacuration_integrated.xlsx"
WARN  File Upload          0:1446:0:1417 No such file: "/Applications/KNIME 3.7.0.app/Contents/MacOS/C:\Users\dgadaleta\Desktop\Milano\progetti in corso\data curation\dataset\solubility.xlsx"
WARN  Column Selection     0:1447:0:1422 Column 'NAME' is not part of the table spec anymore.
Auto-guessing default column.
WARN  Column Selection     0:1447:0:1423 Column 'CAS' is not part of the table spec anymore.
Auto-guessing default column.
WARN  Column Rename        0:1447:0:1425:1423 The following columns are configured but no longer exist: "ID", "ID"
WARN  File Upload          0:1447:0:1417 No such file: "/Applications/KNIME 3.7.0.app/Contents/MacOS/C:\Users\dgadaleta\Desktop\Milano\progetti in corso\data curation\ms\referaggio"
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Table Creator        0:1447:0:1412:1405:78:69 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1406:75:69 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1407:75:69 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1404:75:69 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:187:183 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1421:1417:1420:1407:75:69 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1421:1417:1420:187:183 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1421:1417:26:1442:183 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1421:1417:1420:1156:187:183 Node created an empty data table.
WARN  Column Selection     0:1447:0:1422 Column 'NAME' is not part of the table spec anymore.
Auto-guessing default column.
WARN  Table Creator        0:1447:0:1412:1421:1417:1420:1406:75:69 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1421:1417:26:1406:75:69 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1156:187:183 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1421:1417:26:1407:75:69 Node created an empty data table.
WARN  Column Selection     0:1447:0:1423 Column 'CAS' is not part of the table spec anymore.
Auto-guessing default column.
WARN  Column Rename        0:1447:0:1425:1423 The following columns are configured but no longer exist: "ID", "ID"
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Column Selection     0:1447:0:1422 Column 'NAME' is not part of the table spec anymore.
Auto-guessing default column.
WARN  Column Rename        0:1447:0:1425:1423 The following columns are configured but no longer exist: "ID", "ID"
WARN  Table Creator        0:1447:0:1412:1371:1368:183 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1421:1417:26:1436:187:183 Node created an empty data table.
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Column Selection     0:1447:0:1423 Column 'CAS' is not part of the table spec anymore.
Auto-guessing default column.
WARN  Column Rename        0:1447:0:1425:1423 The following columns are configured but no longer exist: "ID", "ID"
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Column Rename        0:1447:0:1425:1423 The following columns are configured but no longer exist: "ID", "ID"
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Column Rename        0:1447:0:1425:1423 The following columns are configured but no longer exist: "ID", "ID"
WARN  Column Rename        0:1447:0:1425:1423 The following columns are configured but no longer exist: "ID", "ID"
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  File Upload          0:1447:0:1417 No such file: "/Applications/KNIME 3.7.0.app/Contents/MacOS/C:\Users\dgadaleta\Desktop\Milano\progetti in corso\data curation\ms\referaggio"
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  File Upload          0:1447:0:1417 No such file: "/Applications/KNIME 3.7.0.app/Contents/MacOS/C:\Users\dgadaleta\Desktop\Milano\progetti in corso\data curation\ms\referaggio"
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
```

I hope this is a helpful log.  If I can trace it in any other way you recommend please let me know.

**Comment by DGadaleta88** [comment]
Hi @benbowen ,
I think you forgot to specify the input columns including the CAS and the name. The correct way to execute the workflow is:

1) Double click on the "Select input" node to browse your input, then execute only this first node (the green play button highlighting only the first node, or right-click to the node that "Execute").
2) Double click on the second node "Select columns and output", then specify the column in your file including the input data, the path and the name of your preliminar output file.
3) Execute the second node, as above.
4) When the second node is green, go to the preliminary output excel file on your desktop and made the "Manual Check".
5) Save the file, than go back to the workflow and double click to the third node "Select output after manual check" to set the path and the name of the final output (it can be the same as the preliminary one).
6) Execute the last node.

The output for your file is here: 
https://drive.google.com/open?id=1pC_NqzhAUHGz-HClpNu5oDg8CGr8rFT8

In your input there are four equal entries, for this reason the output lists only one chemical, with four duplicates. I changed the ID in your input before executing the workflow (8868 to 8871) because duplicate IDs are not allowed in KNIME.
As all the chemicals were immediately included in the "Maintain" list and no chemicals went to the "Manual Check", no user intervention was needed between executing the second and the third node.

I hope this can help. Let me know if you need further help. 
Also, be sure to download the last version of the workflow because I made some adjustments after your first message.

**Comment by benbowen** [comment]
Thanks @DGadaleta88, but I still can't get it to work (even after updating repo).  Can you provide an example file in the repo?  For me, the most helpful example file would be one where the CAS ID is not available for some of the inputs.  I will not have a CAS ID for the majority of my compounds, but will have a SMILES for all compounds.

Here is the log

```
WARN  File Upload          0:1446:0:1417 No such file: "/Applications/KNIME 3.7.0.app/Contents/MacOS/C:\Users\dgadaleta\Desktop\input_datacuration_integrated.xlsx"
WARN  File Upload          0:1446:0:1417 No such file: "/Applications/KNIME 3.7.0.app/Contents/MacOS/C:\Users\dgadaleta\Desktop\input.xlsx"
WARN  LoadWorkflowRunnable            Warnings during load: Status: Warning: A NEW SEMI-AUTOMATED WORKFLOW FOR CHEMICAL DATA RETRIEVAL AND QUALITY CHECKING FOR MODELLING APPLICATIONS_08_02_2019 0 loaded with warnings
WARN  LoadWorkflowRunnable              Status: Warning: A NEW SEMI-AUTOMATED WORKFLOW FOR CHEMICAL DATA RETRIEVAL AND QUALITY CHECKING FOR MODELLING APPLICATIONS_08_02_2019 0
WARN  LoadWorkflowRunnable                Status: Warning: Metanode 0:1446
WARN  LoadWorkflowRunnable                  Status: Warning: WrappedNode Output 0:1446:0:1419
WARN  LoadWorkflowRunnable                    Status: Warning: State has changed from IDLE to CONFIGURED
WARN  LoadWorkflowRunnable                  Status: Warning: State has changed from IDLE to CONFIGURED
WARN  Column Selection     0:1447:0:1422 Column 'CAS' is not part of the table spec anymore.
Auto-guessing default column.
WARN  Column Selection     0:1447:0:1423 Column 'CAS' is not part of the table spec anymore.
Auto-guessing default column.
WARN  Column Rename        0:1447:0:1425:1423 The following columns are configured but no longer exist: "ID", "ID"
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Table Creator        0:1447:0:1412:1421:1417:26:1407:75:69 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1404:75:69 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1407:75:69 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1406:75:69 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:187:183 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1156:187:183 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1421:1417:26:1406:75:69 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1405:78:69 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1421:1417:1420:1406:75:69 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1421:1417:1420:1407:75:69 Node created an empty data table.
WARN  Column Selection     0:1447:0:1422 Column 'CAS' is not part of the table spec anymore.
Auto-guessing default column.
WARN  Column Selection     0:1447:0:1423 Column 'CAS' is not part of the table spec anymore.
Auto-guessing default column.
WARN  Column Rename        0:1447:0:1425:1423 The following columns are configured but no longer exist: "ID", "ID"
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Table Creator        0:1447:0:1412:1371:1379:1430 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1421:1417:26:1442:183 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1421:1417:26:1436:187:183 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1421:1417:1420:187:183 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1421:1417:1434 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1421:1417:1420:1156:187:183 Node created an empty data table.
WARN  Table Creator        0:1447:0:1412:1371:1368:183 Node created an empty data table.
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Column Selection     0:1447:0:1422 Column 'CAS' is not part of the table spec anymore.
Auto-guessing default column.
WARN  Column Selection     0:1447:0:1423 Column 'CAS' is not part of the table spec anymore.
Auto-guessing default column.
WARN  Column Rename        0:1447:0:1425:1423 The following columns are configured but no longer exist: "ID", "ID"
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Column Rename        0:1447:0:1425:1423 The following columns are configured but no longer exist: "ID", "ID"
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Column Rename        0:1447:0:1425:1423 The following columns are configured but no longer exist: "ID", "ID"
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Column Rename        0:1447:0:1425:1423 The following columns are configured but no longer exist: "ID", "ID"
WARN  Column Rename        0:1447:0:1425:1423 The following columns are configured but no longer exist: "ID", "ID"
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
WARN  Cell Splitter (deprecated) 0:1447:0:1412:1399:1398 Input table doesn't contain specified column name.
```

**Comment by DGadaleta88** [comment]
Hi @benbowen 

I included below a zipped file with the fully-executed workflow ("Workflow_with_example_08_02_2019.knwf"), the input file ("example_input.xlsx") that is already loaded in the WF, and the resulting output ("out_db_example.xlsx").

[Workflow_with example_08_02_2019.zip](https://github.com/DGadaleta88/data_curation_workflow/files/2845373/Workflow_with.example_08_02_2019.zip)

[example_input.xlsx](https://github.com/DGadaleta88/data_curation_workflow/files/2845379/example_input.xlsx)

[out_db_example.xlsx](https://github.com/DGadaleta88/data_curation_workflow/files/2845377/out_db_example.xlsx)

It would be useful if you was able to upload your workflow after you tried the execution, so I can try to figure out the problem.

I am afraid that the workflow is built to work with both the name AND the CAS number as input. If you lack the CAS, the only think you can do is to insert "MISSING" in the CAS field and execute the workflow. If SMILES will be found at least from name, the record will be sent to the "Manual Check". At this point, you will be able to check the retrieved SMILES and decide if confirm it before producing the final output.

If you already have SMILES for your chemicals and you only want to make the structural curation part, you can use the workflow "data_curation_SMILES_input_08_02_2019.knwf" below. 
This is only a part of the bigger, main workflow that may be more suitable to adress your problem. Simply copy-paste the IDs and the SMILES in the input node, and execute the whole workflow.

[data_curation_SMILES_input_08_02_2019.zip](https://github.com/DGadaleta88/data_curation_workflow/files/2845367/data_curation_SMILES_input_08_02_2019.zip)

**Comment by benbowen** [comment]
I've never used knime; so sorry for the basic questions, but how do I add an input layer to your smaller workflow?  The one you sent has data pre-loaded.
![image](https://user-images.githubusercontent.com/810953/52483644-4cb4f980-2b69-11e9-843f-284fa82a986c.png)

Looking into the workflow, I'm not 100% sure it will do what I want.  Perhaps you can confirm or enlighten me.  I seek to identify a canonical tautomer for a set of tautomers.  I've been using MolVS for this with fairly good results, but am always on the look out for alternatives. Tautomers are a really tough problem when maintaining a chemical database (I'm sure you know).

For example, this molecule:
![image](https://user-images.githubusercontent.com/810953/52483772-8dad0e00-2b69-11e9-801e-b2dc93e8809d.png)

has the following tautomers:
![image](https://user-images.githubusercontent.com/810953/52483799-9998d000-2b69-11e9-9ec6-f66a75cfaa13.png)

I'm trying to understand if your workflow can identify a specific one of these tautomers as the canonical form.  Here are the corresponding SMILES to the structures drawn above.

ID     smiles	
0	NC(Cc1c[nH]cn1)=C(O)O
1	NC(=Cc1cnc[nH]1)C(O)O
2	NC(Cc1c[nH]cn1)C(=O)O
3	N=C(Cc1c[nH]cn1)C(O)O
4	NC(Cc1cnc[nH]1)=C(O)O
5	NC(C=C1C=NC=N1)C(O)O
6	N=C(Cc1cnc[nH]1)C(O)O
7	NC(Cc1cnc[nH]1)C(=O)O
8	NC(Cc1cnc[nH]1)C(=O)O
9	NC(Cc1c[nH]cn1)C(=O)O
10	NC(=Cc1c[nH]cn1)C(O)O

**Comment by DGadaleta88** [comment]
@benbowen 

In this case, you simply need to double click on the first node, cancel the input data and paste your list. Below the executed workflow with your input:

[data_curation_SMILES_input_08feb2019.zip](https://github.com/DGadaleta88/data_curation_workflow/files/2845572/data_curation_SMILES_input_08feb2019.zip)

But I am afraid the workflow is not able to adress your issue. The only think that the workflow does is to check if a chemical is included twice or more times in the input list with different tautomeric forms, in order to identify duplicates. It is not able to identify the most stable tautomer. 

As you correcly said, tautomers are a tought issue. While in some cases understanding which is the "winner" tautomer is easy (e.g. the molecule you proposed), in other cases different forms are equally (or closely) stable. I had difficulties in finding a solution in KNIME that consistently returned the same "canonical" tautomer for a given molecule, irrespective of the input form, without considering complex energy calculations.
The OpenBabel node, that here produce canonical SMILES, returns different SMILES for the molecules you listed, but they are all correctly identified as duplicates.

I will be happy to check the MolVS you proposed for a possible future implementation.

**Comment by benbowen** [comment]
Thanks for helping me understand @DGadaleta88! I'll close the issue.  I've been meaning to try OpenBabel.  I'll check it out.
