### ISSUE TITLE
Organozinc compounds not treated as organometallic

### ISSUE THREAD

**Issue by DocMinus** [DGadaleta88/data_curation_workflow#2]
Organozinc compounds are detected as "unusual elements". The RuleEngine node with following Metanode detecting different metals should contain "Zn" as well.

**Comment by DGadaleta88** [comment]
Many thanks, I will update the node at the next release!
However please note that the "Organometallic" check is made on counterions, while the "Unusual element" check is made on the main molecule. For this reason, is no separation (i.e., a dot) is explicitated in the initial SMILES between the main molecule and the counterion, the Zn atom will still cause an "unusual element" flag by the workflow.

**Comment by DocMinus** [comment]
Thanks. I guess I didn’t dig deep enough to notice that detail.

Regards,

Alex
